//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWitcher.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheWitcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_2_zip {
            get {
                object obj = ResourceManager.GetObject("_1_2_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_3_zip {
            get {
                object obj = ResourceManager.GetObject("_1_3_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_4_zip {
            get {
                object obj = ResourceManager.GetObject("_1_4_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_1_zip {
            get {
                object obj = ResourceManager.GetObject("_2_1_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_2_zip {
            get {
                object obj = ResourceManager.GetObject("_2_2_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_4_zip {
            get {
                object obj = ResourceManager.GetObject("_2_4_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_1_zip {
            get {
                object obj = ResourceManager.GetObject("_3_1_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_2_zip {
            get {
                object obj = ResourceManager.GetObject("_3_2_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_3_zip {
            get {
                object obj = ResourceManager.GetObject("_3_3_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_1_zip {
            get {
                object obj = ResourceManager.GetObject("_4_1_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_2_zip {
            get {
                object obj = ResourceManager.GetObject("_4_2_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_3_zip {
            get {
                object obj = ResourceManager.GetObject("_4_3_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_4_zip {
            get {
                object obj = ResourceManager.GetObject("_4_4_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_1_zip {
            get {
                object obj = ResourceManager.GetObject("_5_1_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_2_zip {
            get {
                object obj = ResourceManager.GetObject("_5_2_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кого Геральт искал с Весемиров в начале игры?_Цири_Трисс_Ламберта_Йеннифер_4
        ///Кого Геральт не смог защитить от Дикой охоты в кошмаре?_Трисс_Роше_Цири_Лютика_3
        ///Куда направлялись Геральт и Весемир?_В Новиград_В Белый сад_В Велен_В Москву_2
        ///Кто предложил Геральту найти Цири?_Эмгыр_Йеннифер_Радовид_Лето из Гулето_1
        ///Как называется крепость ведьмаков Школы Волка, в которую отправился Весемир?_Каер Морхен_Арга форт_Ваньпин_Голконда_1
        ///Как звали бывшую любовь, которую Геральт встретил в Новиграде?_Кейра_Трисс_Ци [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кто написал сагу о Ведьмаке?_Марк Твен_А.С. Пушкин_Эрнест Хемингуэй_Анджей Сапковский_4
        ///В каком году был написан первый рассказ цикла?_1993_1945_1986_2004_3
        ///Какую страну напоминает мир &quot;Ведьмака&quot;?_Америку, времён колонизации_Европу, времён позднего средневековья_Древнюю Азию_Современную Россию_2
        ///Сколько игр было выпущено по вселенной &quot;Ведьмак&quot;?_4_5_6_7_1
        ///Что является основной работой Геральта?_Убивать не разумных чудовищ_Быть наемником и убивать людей_Разносить еду_Убивать королей_1
        ///Как звали приемную  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string T1 {
            get {
                return ResourceManager.GetString("T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Из-за какой чумы людей не пускают без грамоты в Вызиму?_Коронавирус_Эбола_Свиной Грипп_Катриона_4
        ///Что является грядущим концом света?_Метеорит_Желтый снег_Белый хлад_Черный свет_3
        ///Как зовут рыжую медичку, давнюю знакомую Геральта?_Цири_Шани_Мани_Вельгефорц_2
        ///Зачем Геральт обращается к Преподобному?_Помочь найти Саламандр_Получить грамоту для прохода в Вызиму_Вылечиться от смертельной болезни_Попросить золота_1
        ///За что Геральта сажают в темницу?_За грамоту_За то, что он ведьмак_За разбои и грабежи_Из-за л [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string T2 {
            get {
                return ResourceManager.GetString("T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В чью засаду попал Геральт в Флоатзаме?_Бандитов_Радовида_Гендальфа_Иорвета_4
        ///Как зовут старого друга-барта Геральта?_Весемир_Василёк_Лютик_Ромашка_3
        ///Продолжите прозвище &quot;Лето из ...&quot;_Котлето_Гулето_Вермето_Зимето_2
        ///Кто похитил Трисс?_Лето_Осень_Зима_Весна_1
        ///С кем Геральт поддерживает восстание против короля Хенсельта?_С Иорветом_С Роше_С Корветтом_С Митсубиси_1
        ///Кто контролировал разум Саскии?_Геральт_Филиппа_Иорвет_Накер_2
        ///В какой город Геральт отправился после Верхнего Аэдирна?_Велен_Флотзам_Лок Муи [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string T3 {
            get {
                return ResourceManager.GetString("T3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кого Геральт искал с Весемиров в начале игры?_Цири_Трисс_Ламберта_Йеннифер_4
        ///Кого Геральт не смог защитить от Дикой охоты в кошмаре?_Трисс_Роше_Цири_Лютика_3
        ///Куда направлялись Геральт и Весемир?_В Новиград_В Белый Сад_В Велен_В Москву_2
        ///Кто предложил геральту найти Цири?_Эмгыр_Йеннифер_Радовид_Лето из Гулето_1
        ///Как называется крепость ведьмаков школы волка, в которую отправился Весемир?_Каер Морхен_Арга Форт_Ваньпин_Голконда_1
        ///Как звали бывшую любовь, которую Геральт встретил в Новиграде?_Кейра_Трисс_Ци [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string T4 {
            get {
                return ResourceManager.GetString("T4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На каком стриминг-сервисе был представлен сериал?_Youtube_Okko_Twitch_Netflix_4
        ///Когда была премьера первого сезона?_21 марта 2016_9 января 2020_20 декабря 2019_15 мая 2018_3
        ///Сюжет каких книг отображен в первом сезоне?_Двух последних_Первых двух_Первых четырех_Всех 9_2
        ///Кто исполняет роль Геральта в сериале?_Генри Кевил_Чарльз Ксавьер_Леонардо Ди Каприо_Брэд Питт_1
        ///Сколько было просмотров у первого сезона за первый месяц?_Более 76 миллионов_Более 10 милллионов_Около 2 миллиардов_Более 700 тысяч_1.
        /// </summary>
        internal static string T5 {
            get {
                return ResourceManager.GetString("T5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_TheWitcher {
            get {
                object obj = ResourceManager.GetObject("text_TheWitcher", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TheWitcher_bg_SuperZip {
            get {
                object obj = ResourceManager.GetObject("TheWitcher_bg_SuperZip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap witcher_logo_SuperZip {
            get {
                object obj = ResourceManager.GetObject("witcher_logo_SuperZip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
